INSERT INTO USER VALUES(null,'a1','男');
INSERT INTO USER VALUES(null,'b2','男');
INSERT INTO USER VALUES(null,'c3','男')
INSERT INTO USER VALUES(null,'d4','女')
INSERT INTO USER VALUES(null,'e5','男')
INSERT INTO USER VALUES(null,'f6','男')