package com.tianxiaxinyong.mapper;

import com.tianxiaxinyong.enterprise.member.domain.MemberRole;

public interface MemberRoleMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_role
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_role
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    int insert(MemberRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_role
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    MemberRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_role
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    int updateByPrimaryKeySelective(MemberRole record);

}