package com.tianxiaxinyong.enterprise.member.domain;

import java.io.Serializable;
import java.util.Date;

public class MemberRole implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -5589653297816095491L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_role.id
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_role.member_id
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    private String memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_role.role_id
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_role.create_time
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_role.update_time
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_role.id
     *
     * @return the value of member_role.id
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_role.id
     *
     * @param id the value for member_role.id
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_role.member_id
     *
     * @return the value of member_role.member_id
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_role.member_id
     *
     * @param memberId the value for member_role.member_id
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_role.role_id
     *
     * @return the value of member_role.role_id
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_role.role_id
     *
     * @param roleId the value for member_role.role_id
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_role.create_time
     *
     * @return the value of member_role.create_time
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_role.create_time
     *
     * @param createTime the value for member_role.create_time
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_role.update_time
     *
     * @return the value of member_role.update_time
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_role.update_time
     *
     * @param updateTime the value for member_role.update_time
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}