package com.tianxiaxinyong.enterprise.member.domain;

import java.io.Serializable;
import java.util.Date;

public class Member implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 8240103173290490895L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.id
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.username
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.password
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.nickname
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.email
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.email_status
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    private Integer emailStatus;
    
    /**
     * @category 登陆失败次数
     */
    private Integer loginFailtimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.mobile
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.company_name
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.user_status
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    private Integer userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.last_logintime
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    private Date lastLogintime;
    
    
    private Date locktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.last_loginip
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    private String lastLoginip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.create_time
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.update_time
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.id
     *
     * @return the value of member.id
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.id
     *
     * @param id the value for member.id
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.username
     *
     * @return the value of member.username
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.username
     *
     * @param username the value for member.username
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.password
     *
     * @return the value of member.password
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.password
     *
     * @param password the value for member.password
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.nickname
     *
     * @return the value of member.nickname
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.nickname
     *
     * @param nickname the value for member.nickname
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.email
     *
     * @return the value of member.email
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.email
     *
     * @param email the value for member.email
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.email_status
     *
     * @return the value of member.email_status
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public Integer getEmailStatus() {
        return emailStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.email_status
     *
     * @param emailStatus the value for member.email_status
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public void setEmailStatus(Integer emailStatus) {
        this.emailStatus = emailStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.mobile
     *
     * @return the value of member.mobile
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.mobile
     *
     * @param mobile the value for member.mobile
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.company_name
     *
     * @return the value of member.company_name
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.company_name
     *
     * @param companyName the value for member.company_name
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.user_status
     *
     * @return the value of member.user_status
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public Integer getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.user_status
     *
     * @param userStatus the value for member.user_status
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.last_logintime
     *
     * @return the value of member.last_logintime
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public Date getLastLogintime() {
        return lastLogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.last_logintime
     *
     * @param lastLogintime the value for member.last_logintime
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public void setLastLogintime(Date lastLogintime) {
        this.lastLogintime = lastLogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.last_loginip
     *
     * @return the value of member.last_loginip
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public String getLastLoginip() {
        return lastLoginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.last_loginip
     *
     * @param lastLoginip the value for member.last_loginip
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public void setLastLoginip(String lastLoginip) {
        this.lastLoginip = lastLoginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.create_time
     *
     * @return the value of member.create_time
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.create_time
     *
     * @param createTime the value for member.create_time
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.update_time
     *
     * @return the value of member.update_time
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.update_time
     *
     * @param updateTime the value for member.update_time
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public Date getLocktime() {
		return locktime;
	}

	public void setLocktime(Date locktime) {
		this.locktime = locktime;
	}

	public Integer getLoginFailtimes() {
		return loginFailtimes;
	}

	public void setLoginFailtimes(Integer loginFailtimes) {
		this.loginFailtimes = loginFailtimes;
	}
	
	
}