package com.tianxiaxinyong.enterprise.member.domain;

import java.io.Serializable;
import java.util.Date;

public class Role implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -8311005083353648720L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_name
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_value
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    private String roleValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_status
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    private Integer roleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.create_time
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.update_time
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_name
     *
     * @return the value of role.role_name
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_name
     *
     * @param roleName the value for role.role_name
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_value
     *
     * @return the value of role.role_value
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public String getRoleValue() {
        return roleValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_value
     *
     * @param roleValue the value for role.role_value
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public void setRoleValue(String roleValue) {
        this.roleValue = roleValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_status
     *
     * @return the value of role.role_status
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public Integer getRoleStatus() {
        return roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_status
     *
     * @param roleStatus the value for role.role_status
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public void setRoleStatus(Integer roleStatus) {
        this.roleStatus = roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.create_time
     *
     * @return the value of role.create_time
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.create_time
     *
     * @param createTime the value for role.create_time
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.update_time
     *
     * @return the value of role.update_time
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.update_time
     *
     * @param updateTime the value for role.update_time
     *
     * @mbggenerated Tue Apr 05 14:32:47 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}